import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.sass";
import { Header } from "@/components";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={outfit.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
